### PR TITLE
Fix Authentication Header

### PR DESCRIPTION
**Pull request by MohamedGamil**
**The latest API of CoinJar requires Authentication Header to be sent as follows:**
`Authentication: Bearer [API-SECRET-TOKEN]`

**Instead of:**
`Authentication: Token token="[API-SECRET-TOKEN]"`

### CODE REVIEW

**Comment by sketchthat** [comment]
It appears both work, but I checked the documentation and I don't see  the change; https://docs.exchange.coinjar.com/trading-api/#/introduction/authentication

Are you able to point me to where you saw the update?

**Comment by MohamedGamil** [comment]
The change was discovered during tests performed on both the actual API and the sandbox versions, it appears that using the old syntax mentioned in CoinJar documentation doesn't work for me, and trying the new syntax mentioned in the pull request worked without problems, I'm not sure why that's the case though.

If it works for you then never mind approving the pull request bro <3

**Comment by sketchthat** [comment]
I've sent off a request to CoinJar support to check what their API is going to continue to support, then I'll work out the merge.

Thanks @MohamedGamil

**Comment by sketchthat** [comment]
I heard back from CoinJar Support and they said;

> I've confirmed with our Engineering Team that there's no changes to our API - the information specified in our official API documentation is correct.

I'm going to close this PR because it looks like `Authentication: Token token="[API-SECRET-TOKEN]"` is still the correct authentication method.

**Pull request closed without merging**
